PERCEPTION_URL = "https://static-content.springer.com/esm/art%3A10.1186%2Fs12868-016-0287-2/MediaObjects/12868_2016_287_MOESM1_ESM.xlsx"
ODOR_PERCEPT_COL = ['EDIBLE', 'BAKERY', 'SWEET', 'FRUIT', 'FISH', 'GARLIC', 'SPICES', 'COLD', 'SOUR', 'BURNT',
                    'ACID', 'WARM', 'MUSKY', 'SWEATY', 'AMMONIA/URINOUS', 'DECAYED', 'WOOD', 'GRASS', 'FLOWER',
                    'CHEMICAL']
IGNOR_ODORS = ['CHEMICAL']
CID_INDEX_HEADER = 'CID'
ODOR_DILUTION = 'Odor dilution'
FREQUENCY_THRESHOLD = 10
HIGH_DILUTION = '1'
LOW_DILUTION = '0'
